[project]
name = "ha-zzu-energy"
version = "0.1.0"
description = "一个 Home Assistant 集成，用于监控郑州大学宿舍电量"
requires-python = ">=3.13.2,<4"
dependencies = [
    "homeassistant>=2025.9.1",
    "zzupy>=6.0.0rc7",
]

[project.optional-dependencies]
ci = [
  "ruff>=0.13.2"
]
