[project]
name = "ha-zzu-energy"
version = "0.1.0"
description = "一个 Home Assistant 集成，用于监控郑州大学宿舍电量"
requires-python = ">=3.11"
dependencies = [
    "homeassistant>=2025.9.1",
    "zzupy>=6.0.0rc7",
]
